# Bloggy particulars
highlighter: "rouge"
permalink: "/:year/:title"
name: "William Ellison('s Blog)"
description: "A Web developer in Knoxville, Tennessee"
future: false

plugins: ["jekyll-paginate"]

url: https://waellison.blog
paginate: 5
excerpt_separator: "\n\n"

# Personal particulars
person:
  name: William Ellison
  email: waellison@gmail.com
  occupation: Web Developer

encoding: UTF-8
exclude: 
  - "Gemfile"
  - "Rakefile"
  - "Gemfile.lock"
  - "deploy.sh"
