source 'https://rubygems.org'

gem 'rake'
gem 'rouge'
gem 'nokogiri'
gem 'mercenary'
gem 'liquid'
gem 'jekyll'
gem 'webrick'
gem 'jekyll-sitemap'
gem 'jekyll-paginate'
gem 'liquid_reading_time'
gem 'os'
